/* Orbital-mechanics helpers for the browser visualisation.
 * Planetary states are interpolated from static NASA/JPL DE440s samples
 * generated by q1_q3_final/scripts/run_de440s_lambert_porkchop.py. */
(function (global) {
  "use strict";

  const DATA = global.MarsDE440sData || null;
  const C = DATA ? DATA.constants : {};
  const MU_SUN = C.muSunM3S2 || 1.3271244004127938e20;
  const MU_EARTH = C.muEarthM3S2 || 3.986004355070226e14;
  const MU_MARS = C.muMarsM3S2 || 4.282837362069909e13;
  const AU = C.auM || 1.495978706136889e11;
  const R_EARTH = C.radiusEarthM || 6378136.6;
  const R_MARS = C.radiusMarsM || 3396190.0;
  const DAY = 86400.0;

  function sub(a, b) { return [a[0]-b[0], a[1]-b[1], a[2]-b[2]]; }
  function add(a, b) { return [a[0]+b[0], a[1]+b[1], a[2]+b[2]]; }
  function scale(a, s) { return [a[0]*s, a[1]*s, a[2]*s]; }
  function dot(a, b) { return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]; }
  function cross(a, b) {
    return [a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0]];
  }
  function norm(a) { return Math.sqrt(dot(a, a)); }

  function julianDate(y, m, d, hh, mm, ss) {
    hh = hh || 0; mm = mm || 0; ss = ss || 0;
    if (m <= 2) { y -= 1; m += 12; }
    const A = Math.floor(y / 100);
    const B = 2 - A + Math.floor(A / 4);
    let jd = Math.floor(365.25 * (y + 4716)) + Math.floor(30.6001 * (m + 1)) + d + B - 1524.5;
    jd += (hh + mm / 60 + ss / 3600) / 24;
    return jd;
  }

  function jdFromIso(value) {
    const m = /^(\d{4})-(\d{2})-(\d{2})(?:[T\s](\d{2}):(\d{2}))?/.exec(String(value));
    if (!m) throw new Error("Invalid date: " + value);
    return julianDate(+m[1], +m[2], +m[3], +(m[4] || 0), +(m[5] || 0), 0);
  }

  function jdToIso(jd) {
    jd += 0.5;
    let Z = Math.floor(jd), F = jd - Z, A;
    if (Z < 2299161) A = Z;
    else {
      const alpha = Math.floor((Z - 1867216.25) / 36524.25);
      A = Z + 1 + alpha - Math.floor(alpha / 4);
    }
    const B = A + 1524;
    const Cc = Math.floor((B - 122.1) / 365.25);
    const D = Math.floor(365.25 * Cc);
    const E = Math.floor((B - D) / 30.6001);
    const dayFloat = B - D - Math.floor(30.6001 * E) + F;
    const month = E < 14 ? E - 1 : E - 13;
    const year = month > 2 ? Cc - 4716 : Cc - 4715;
    const day = Math.floor(dayFloat);
    const frac = dayFloat - day;
    const minutes = Math.round(frac * 24 * 60);
    const hh = Math.floor(minutes / 60);
    const mm = minutes % 60;
    const p = n => (n < 10 ? "0" : "") + n;
    return `${year}-${p(month)}-${p(day)}${minutes ? ` ${p(hh)}:${p(mm)}` : ""}`;
  }

  function interpolateSample(samples, jd) {
    if (!DATA) throw new Error("DE440s data file is not loaded");
    const eph = DATA.ephemeris;
    const x = (jd - eph.jd0) / eph.stepDays;
    let i = Math.floor(x);
    if (i < 0 || i >= samples.length - 1) throw new Error("Date is outside the DE440s sample span");
    const f = x - i;
    const a = samples[i], b = samples[i + 1];
    const p = k => (a[k] + (b[k] - a[k]) * f);
    return {
      r: [p(0) * AU, p(1) * AU, p(2) * AU],
      v: [p(3) * 1000, p(4) * 1000, p(5) * 1000],
    };
  }

  function planetState(name, jd) {
    const eph = DATA && DATA.ephemeris;
    if (!eph) throw new Error("DE440s ephemeris data is not loaded");
    const key = String(name).toLowerCase();
    if (key === "earth") return interpolateSample(eph.earth, jd);
    if (key === "mars") return interpolateSample(eph.mars, jd);
    throw new Error("Unknown planet: " + name);
  }

  function solveKepler(M, e) {
    M = ((M + Math.PI) % (2*Math.PI) + 2*Math.PI) % (2*Math.PI) - Math.PI;
    let E = M + e * Math.sin(M);
    for (let i = 0; i < 100; i++) {
      const dE = -(E - e*Math.sin(E) - M) / (1 - e*Math.cos(E));
      E += dE;
      if (Math.abs(dE) < 1e-12) break;
    }
    return E;
  }

  function trueFromEcc(E, e) {
    return 2*Math.atan2(Math.sqrt(1+e)*Math.sin(E/2), Math.sqrt(1-e)*Math.cos(E/2));
  }

  function elementsToState(a, e, I, Om, om, nu, mu) {
    mu = mu || MU_SUN;
    const p = a * (1 - e*e);
    const r = p / (1 + e*Math.cos(nu));
    const rpf = [r*Math.cos(nu), r*Math.sin(nu), 0];
    const k = Math.sqrt(mu / p);
    const vpf = [-k*Math.sin(nu), k*(e + Math.cos(nu)), 0];
    const cO=Math.cos(Om), sO=Math.sin(Om), cI=Math.cos(I), sI=Math.sin(I), co=Math.cos(om), so=Math.sin(om);
    const R = [
      [cO*co - sO*so*cI, -cO*so - sO*co*cI,  sO*sI],
      [sO*co + cO*so*cI, -sO*so + cO*co*cI, -cO*sI],
      [so*sI,             co*sI,              cI],
    ];
    function mul(M, v) {
      return [M[0][0]*v[0]+M[0][1]*v[1]+M[0][2]*v[2],
              M[1][0]*v[0]+M[1][1]*v[1]+M[1][2]*v[2],
              M[2][0]*v[0]+M[2][1]*v[1]+M[2][2]*v[2]];
    }
    return { r: mul(R, rpf), v: mul(R, vpf) };
  }

  function stumpffC(z) {
    if (z > 1e-9) { const s=Math.sqrt(z); return (1-Math.cos(s))/z; }
    if (z < -1e-9){ const s=Math.sqrt(-z); return (Math.cosh(s)-1)/(-z); }
    return 0.5 - z/24 + z*z/720;
  }
  function stumpffS(z) {
    if (z > 1e-9) { const s=Math.sqrt(z); return (s-Math.sin(s))/(s*s*s); }
    if (z < -1e-9){ const s=Math.sqrt(-z); return (Math.sinh(s)-s)/(s*s*s); }
    return 1/6 - z/120 + z*z/5040;
  }

  function lambert(r1, r2, dt, mu, prograde) {
    mu = mu || MU_SUN;
    if (prograde === undefined) prograde = true;
    const R1 = norm(r1), R2 = norm(r2);
    const cr = cross(r1, r2);
    let cosdnu = dot(r1, r2) / (R1*R2);
    cosdnu = Math.max(-1, Math.min(1, cosdnu));
    let dnu;
    if (prograde) dnu = (cr[2] >= 0) ? Math.acos(cosdnu) : 2*Math.PI-Math.acos(cosdnu);
    else dnu = (cr[2] < 0) ? Math.acos(cosdnu) : 2*Math.PI-Math.acos(cosdnu);
    const A = Math.sin(dnu) * Math.sqrt(R1*R2 / (1 - cosdnu));
    if (Math.abs(A) < 1e-30) return null;
    function yOf(z) {
      return R1 + R2 + A*(z*stumpffS(z) - 1)/Math.sqrt(stumpffC(z));
    }
    function F(z) {
      const C = stumpffC(z), S = stumpffS(z);
      const y = R1 + R2 + A*(z*S - 1)/Math.sqrt(C);
      return Math.pow(y/C, 1.5)*S + A*Math.sqrt(y) - Math.sqrt(mu)*dt;
    }
    let zlo = -4*Math.PI*Math.PI, zhi = 4*Math.PI*Math.PI - 1e-6;
    while (yOf(zlo) < 0 && zlo < zhi) zlo += 0.1;
    let Flo = F(zlo), Fhi = F(zhi);
    if (!isFinite(Flo) || !isFinite(Fhi) || Flo*Fhi > 0) return null;
    let z = 0.5*(zlo+zhi);
    for (let i = 0; i < 2000; i++) {
      const Fz = F(z);
      if (Math.abs(Fz) < 1e-6*Math.sqrt(mu)*dt || (zhi-zlo) < 1e-10) break;
      if (Flo*Fz < 0) zhi = z; else { zlo = z; Flo = Fz; }
      z = 0.5*(zlo+zhi);
    }
    const y = yOf(z);
    const f = 1 - y/R1, g = A*Math.sqrt(y/mu), gd = 1 - y/R2;
    return {
      v1: scale(sub(r2, scale(r1, f)), 1/g),
      v2: scale(sub(scale(r2, gd), r1), 1/g),
    };
  }

  function hohmann(r1, r2, mu) {
    mu = mu || MU_SUN;
    const at = 0.5*(r1+r2);
    const vc1 = Math.sqrt(mu/r1), vc2 = Math.sqrt(mu/r2);
    const vp = Math.sqrt(mu*(2/r1 - 1/at)), va = Math.sqrt(mu*(2/r2 - 1/at));
    const dv1 = vp - vc1, dv2 = vc2 - va;
    const tof = Math.PI*Math.sqrt(at*at*at/mu);
    const n1 = Math.sqrt(mu/(r1*r1*r1)), n2 = Math.sqrt(mu/(r2*r2*r2));
    const alpha = Math.PI - n2*tof;
    const Te = 2*Math.PI / n1;
    const Tm = 2*Math.PI / n2;
    const Tsyn = 2*Math.PI/Math.abs(n1 - n2);
    return { at, et:(r2-r1)/(r2+r1), vc1, vc2, vp, va, dv1, dv2,
             dvTotal: Math.abs(dv1)+Math.abs(dv2), tof, alpha, Te, Tm, Tsyn };
  }

  function patchedConicDv(vinf, mu, radius, altitude) {
    const rp = radius + altitude;
    return Math.sqrt(vinf*vinf + 2*mu/rp) - Math.sqrt(mu/rp);
  }

  global.Astro = {
    MU_SUN, MU_EARTH, MU_MARS, AU, DAY, R_EARTH, R_MARS,
    sub, add, scale, dot, cross, norm,
    julianDate, jdFromIso, jdToIso, solveKepler, trueFromEcc,
    elementsToState, planetState, lambert, hohmann, stumpffC, stumpffS,
    patchedConicDv,
  };
})(typeof window !== "undefined" ? window : globalThis);
