/* Bilingual (zh / en) string table and helper. */
(function (global) {
  "use strict";

  const STR = {
    title: ["飞向火星 · 地火轨道转移可视化", "Going to Mars · Earth-Mars Transfer Visualiser"],
    subtitle: ["MATH2850J 项目一 · 交互式补充材料", "MATH2850J Project 1 · Interactive supplement"],
    tab_hohmann: ["霍曼转移", "Hohmann"],
    tab_porkchop: ["Lambert / Porkchop", "Lambert / Porkchop"],
    tab_three: ["3D 真实转移", "3D transfer"],
    tab_formulas: ["公式与数据来源", "Formulas & Sources"],
    play: ["暂停", "Pause"],
    paused: ["播放", "Play"],
    reset: ["重置", "Reset"],

    h_title: ["霍曼转移动画", "Hohmann transfer"],
    h_desc: ["两条共面圆轨道之间的最省能二脉冲转移。拖动滑块可观察理想圆轨道半径改变时的速度增量、飞行时间和相位角。", "The minimum-energy two-impulse transfer between two coplanar circular orbits. Drag the sliders to see how the burns, flight time, and phase angle change."],
    h_r1: ["出发轨道半径 r1 (AU)", "Departure radius r1 (AU)"],
    h_r2: ["目标轨道半径 r2 (AU)", "Target radius r2 (AU)"],
    h_speed: ["动画速度", "Animation speed"],
    h_preset: ["地球到火星", "Earth to Mars"],
    r_dv1: ["Δv1 (出发)", "Δv1 (depart)"],
    r_dv2: ["Δv2 (到达)", "Δv2 (arrive)"],
    r_dvtot: ["总 Δv (日心)", "Total Δv (helio)"],
    r_tof: ["飞行时间", "Time of flight"],
    r_syn: ["会合周期", "Synodic period"],
    r_phase: ["发射相位角", "Phase angle"],

    p_title: ["Lambert / Porkchop", "Lambert / Porkchop"],
    p_window: ["发射窗口", "Launch window"],
    p_optkind: ["定位方案", "Design to locate"],
    p_findopt: ["定位", "Locate"],
    pc_cap1: ["上图为总 Δv，下图为 C3；横轴为发射日偏移，纵轴为飞行时间。点击任一图的点会同步选择同一日期对。", "Top: total Δv. Bottom: C3. The x-axis is departure offset and the y-axis is time of flight. Clicking either plot selects the same date pair."],
    pc_cap2: ["对应日心俯视轨迹。", "Corresponding heliocentric top-view trajectory."],
    p_dep: ["发射时间", "Departure"],
    p_arr: ["到达时间", "Arrival"],
    p_totaldv: ["总 Δv", "Total Δv"],
    p_ready: ["DE440s/Lambert 静态网格已载入。点击图中任一点读取该转移。", "DE440s/Lambert static grid loaded. Click any point to inspect that transfer."],
    opt_min_total: ["最小总 Δv", "Minimum total Δv"],
    opt_min_c3: ["最小 C3", "Minimum C3"],
    opt_fast: ["快而不超支过多", "Fast within budget"],
    opt_pareto: ["Pareto 折中", "Pareto compromise"],

    t_title: ["3D 真实转移", "3D real transfer"],
    t_dep: ["发射日偏移 (天)", "Departure offset (days)"],
    t_tof: ["飞行时间 (天)", "Time of flight (days)"],
    t_topview: ["切换视角", "Toggle view"],
    t_inc: ["转移轨道倾角", "Transfer inclination"],
    t_speed: ["动画速度", "Animation speed"],
    t_depdate: ["发射时间", "Departure"],
    t_arrdate: ["到达时间", "Arrival"],
    t_best: ["最佳 Δv", "Best Δv"],

    f_part1: ["第 i 部分", "Part i"],
    f_part2: ["第 ii 部分", "Part ii"],
    f_part3: ["第 iii 部分", "Part iii"],
    f_sources: ["数据来源", "Data sources"],
    foot: ["Lambert 网格、候选轨迹和行星状态均由本项目 Python 代码基于 NASA/JPL DE440s 生成。", "Lambert grids, candidate trajectories, and planetary states are generated by the project Python code from NASA/JPL DE440s."],
  };

  let lang = 0;
  function t(key) { return STR[key] ? STR[key][lang] : key; }
  function setLang(l) { lang = l; apply(); }
  function getLang() { return lang; }
  function apply() {
    document.documentElement.lang = lang ? "en" : "zh";
    document.querySelectorAll("[data-i18n]").forEach(el => {
      const key = el.getAttribute("data-i18n");
      if (STR[key]) el.textContent = STR[key][lang];
    });
    if (global.onLangChange) global.onLangChange();
  }

  global.I18N = { t, setLang, getLang, apply, STR };
})(window);
